In [1]:
import numpy as np
import cv2 as cv

In [2]:
# mouse callback function
def draw_circle(event,x,y,flags,param):
    if event == cv.EVENT_LBUTTONDBLCLK:
        print(imgRsz[y,x]) #img[width,height]
        #cv.circle(img,(x,y),100,(255,0,0),-1)

In [7]:
# Create a black image, a window and bind the function to window
#img = np.zeros((512,512,3), np.uint8)
path = "D:/Project/AI_Med/"
file = "greyImg.jpg"
file1 = "55.jpg"
imgPath = path+file
wrtInvAndImg = "invAndImg.jpg"
img = cv.imread(imgPath)
imgRsz = cv.resize(img, (960, 540)) 
cv.namedWindow('image')
cv.setMouseCallback('image',draw_circle)
 
while(1):
    cv.imshow('image',imgRsz)
    if cv.waitKey(20) & 0xFF == 27:
        break
cv.destroyAllWindows()

[180 180 180]
[200 200 200]
[208 208 208]
[188 188 188]
